### PR TITLE
NVIDIA 470.129.06

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/188877/en-us

### CODE REVIEW

**Comment by linuxgnuru** [comment]
Test results, tested on kudu6, thelio-mira-b1 (nvidia 2080), and thelio-r1-6 (nvidia 710) 

[nvidia-470-test-results.txt](https://github.com/pop-os/nvidia-graphics-drivers-470/files/8766670/nvidia-470-test-results.txt)

NOTE with the 710 the system did not resume from suspend.  Attaching journal log showing kernel oops with driver.

[journal.log](https://github.com/pop-os/nvidia-graphics-drivers-470/files/8766679/journal.log)

**Comment by n3m0-22** [comment]
Tested with `22.04`, `21.10`, `20.04` on `orpy4`. All test passed with the exception of fractional scaling on an external display. Also and this seems specific to the `orpy4` the external display must always be set to the same scaling as the built in display or it gets cut off e.g., if the built in display is 100% and the external is 200% the external will be cut off. This is also a larger cutoff than was seen with the 510 driver. This is just to be noted as it is not a regression.

[nvidia-470-tests.txt](https://github.com/pop-os/nvidia-graphics-drivers-470/files/8782156/nvidia-470-tests.txt)

**Comment by n3m0-22** [comment]
`22.04`, `21.10`, `20.04` on `gaze15` all testing passed with the exception of fractional scaling on an external display over mDP. HDMI fractional scaling is working fine still.

**Comment by linuxgnuru** [comment]
On gaze17-3060-b everything passed except for fractional scaling which doesn't work on HDMI or mDP. 

Tested 22.04 and 20.04 on thelio-r1-6 with nvidia 710 no issues.

Considering the 470 driver is mainly to support the 710, and that the 710 probably can't handle high resolution monitors needing fractional scaling, is this a game breaker?

**Comment by gangwerz** [comment]
Passed testing on Pop and Ubuntu 22.04 on the galp5-1650Ti

Fractional scaling worked over HDMI on this system with either OS, but I do not have USB-C to DisplayPort to test with.

**Pop 22.04**
[nvidia-470.129.06-pop-22.04.md](https://github.com/pop-os/nvidia-graphics-drivers-470/files/9023097/nvidia-470.129.06-pop-22.04.md)

**Ubuntu 22.04**
[nvidia-470.129.06-ubuntu-22.04.md](https://github.com/pop-os/nvidia-graphics-drivers-470/files/9023101/nvidia-470.129.06-ubuntu-22.04.md)

**Comment by leviport** [comment]
>Considering the 470 driver is mainly to support the 710, and that the 710 probably can't handle high resolution monitors needing fractional scaling, is this a game breaker?

Fractional scaling is for high pixel density, not necessarily high resolution. That said, I think that sounds reasonable. I think we can approve and merge this, then release it on Monday.

**Review by leviport — APPROVED** [review]

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
