### PR TITLE
NVIDIA 470.141.03

### PR DESCRIPTION
**Pull request by 13r0ck**
https://www.nvidia.com/Download/driverResults.aspx/191232/en-us/

### CODE REVIEW

**Comment by gangwerz** [comment]
This version of the Nvidia 470 branch also fails to build DKMS when the 5.19 kernel is installed.

`Error! Bad return status for module build on kernel: 5.19.0-76051900-generic (x86_64)`

**Comment by n3m0-22** [comment]
I've added this PR but am still only seeing the 470.129.06 driver.

**Comment by gangwerz** [comment]
The new version has a pin priority of 500, while version 470.129.06 has the 1001 priority level.

**Comment by linuxgnuru** [comment]
Brock is working on it; it did not build initially

**Comment by linuxgnuru** [comment]
on gaze16-3060-b 470 installed on 5.19 with no issues

**Comment by n3m0-22** [comment]
Installed on oryp4 and gaze15 with 5.19 kernel

**Comment by gangwerz** [comment]
Installed on the `galp5-1650Ti` as well! :tada:

**Comment by linuxgnuru** [comment]
On thelio-b2 with Nvidia 2080 with this 470 driver; the decrypt drive screen is only shown on the integrated GPU not the Nvidia.

EDIT: tested with nvidia 710 and same result, the decrypt drive is sent to the integrated display not the display connected to the dedicated GPU

**Comment by n3m0-22** [comment]
Tested on gaze15 and oryp4 with 5.19 kernel in all graphics modes with the latest Steam Flatpak

Proton games are not starting, or start but are non responsive with this driver. 

This error shows for some but not all Proton games:
```
Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed
```

**Comment by linuxgnuru** [comment]
> 

yeah i got that too; you have to set proton to a non-experimental version

**Comment by n3m0-22** [comment]
@linuxgnuru  That works. I had to go back a few more versions of proton for some games than I had initially tried.

**Comment by 13r0ck** [comment]
@linuxgnuru 
>  you have to set proton to a non-experimental version

Do we have support docs that say that?

**Comment by linuxgnuru** [comment]
> @linuxgnuru
> 
> > you have to set proton to a non-experimental version
> 
> Do we have support docs that say that?

nope just had a hunch

**Comment by 13r0ck** [comment]
@Ampersandstorm 
We should probably have docs that suggest [this](https://github.com/pop-os/nvidia-graphics-drivers-470/pull/8#issuecomment-1209612617) as a solution, to [this](https://github.com/pop-os/nvidia-graphics-drivers-470/pull/8#issuecomment-1209595507)

**Review by gangwerz — DISMISSED** [review]
This release has passed testing with 5.19 on the `galp5-1650Ti` as well.

I did not find any regressions, but I was also able to reproduce the Proton Experimental behavior that was reported. The previous Proton version (7.0-3) worked fine for the game I tested with.

**Review by linuxgnuru — CHANGES_REQUESTED** [review]
The driver needs to add support for desktops that have an integrated GPU and an encrypted drive so that the decryption screen is sent to the dedicated GPU and not to the integrated GPU.

**Comment by n3m0-22** [comment]
All testing passed on gaze15 and oryp4

**Review by linuxgnuru — APPROVED** [review]
Fix for integrated GPU with decryption is below:
https://github.com/pop-os/system76-power/pull/311

**Review by mmstick — APPROVED** [review]

**Pull request merged**
