### PR TITLE
470.103.01

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/186016/en-us

### CODE REVIEW

**Review by bflanagin — COMMENTED** [review]
In jammy:
```
xserver-xorg-video-nvidia-470 : Depends: xorg-video-abi-24 but it is not installable or
                                          xorg-video-abi-23 but it is not installable or
                                          xorg-video-abi-20 but it is not installable or
                                          xorg-video-abi-19 but it is not installable or
                                          xorg-video-abi-18 but it is not installable or
                                          xorg-video-abi-15 but it is not installable or
                                          xorg-video-abi-14 but it is not installable or
                                          xorg-video-abi-13 but it is not installable or
                                          xorg-video-abi-12 but it is not installable or
                                          xorg-video-abi-11 but it is not installable or
                                          xorg-video-abi-10 but it is not installable or
                                          xorg-video-abi-8 but it is not installable or
                                          xorg-video-abi-6.0 but it is not installable
```

**Comment by jackpot51** [comment]
I synced the packaging with Ubuntu which should fix that issue

**Review by n3m0-22 — DISMISSED** [review]
In 22.04 this works now. I had an issue the first time I ran it that I could not replicate, but it may have been that I was in integrated graphics mode. Once I switched to hybrid it worked fine. I ran it a second time after uninstalling to be safe with no problems.

```
sudo apt install nvidia-driver-470
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libnvidia-cfg1-470 libnvidia-common-470 libnvidia-compute-470
  libnvidia-compute-470:i386 libnvidia-decode-470 libnvidia-decode-470:i386
  libnvidia-egl-wayland1 libnvidia-encode-470 libnvidia-encode-470:i386
  libnvidia-extra-470 libnvidia-fbc1-470 libnvidia-fbc1-470:i386
  libnvidia-gl-470 libnvidia-gl-470:i386 libnvidia-ifr1-470
  libnvidia-ifr1-470:i386 nvidia-compute-utils-470 nvidia-dkms-470
  nvidia-kernel-common-470 nvidia-kernel-source-470 nvidia-settings
  nvidia-utils-470 xserver-xorg-video-nvidia-470
The following NEW packages will be installed:
  libnvidia-cfg1-470 libnvidia-common-470 libnvidia-compute-470
  libnvidia-compute-470:i386 libnvidia-decode-470 libnvidia-decode-470:i386
  libnvidia-egl-wayland1 libnvidia-encode-470 libnvidia-encode-470:i386
  libnvidia-extra-470 libnvidia-fbc1-470 libnvidia-fbc1-470:i386
  libnvidia-gl-470 libnvidia-gl-470:i386 libnvidia-ifr1-470
  libnvidia-ifr1-470:i386 nvidia-compute-utils-470 nvidia-dkms-470
  nvidia-driver-470 nvidia-kernel-common-470 nvidia-kernel-source-470
  nvidia-settings nvidia-utils-470 xserver-xorg-video-nvidia-470
0 upgraded, 24 newly installed, 0 to remove and 0 not upgraded.
Need to get 287 MB/288 MB of archives.
After this operation, 795 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
```
nvidia-smi 
Wed Apr  6 16:45:04 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0    17W /  N/A |      5MiB /  3911MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2395      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

```

**Review by n3m0-22 — COMMENTED** [review]
In 20.04 this installs correctly and passes all hardware and software test with the exception of running in Compute Graphics. In Compute Graphics the whole system freezes. This happens right at or around login.

**Comment by n3m0-22** [comment]
After further testing of 22.04 a similar issue presented while using Compute Graphics. After several reboots it eventually booted to a black screen after decryption. It never made it to the login screen. It does not completely freeze like 20.04. From the terminal I was able to reboot and got the following error:
```
[  160.042852] pmouse serio1: Failed to disable mouse on isa0060/serio1
[  161.075399] nvidia 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
[  162.260407] snd_hda_intel 000:01:00.1: can't change power state from D3Cold to D0 (config space inaccessible)
```
After a hard reboot I was able to switch the graphics mode from the terminal to Integrated. This fixed the reboot hanging issue but it would still boot to a black screen. I checked with ```system76-power graphics``` and the output was  ```integrated```. I was able to run ```sudo apt purge ~nnvidia``` and rebooted to the GUI successfully. I reinstalled ```nvidia-470.103.01``` and everything worked again except for Compute Graphics. Once again this took several reboots for the problem to happen. The same procedure fixed it.

This can also happen with Hybrid Graphics on 22.04, but is fixed by setting to Integrated from the terminal and rebooting. The problem is intermittent.

**Comment by n3m0-22** [comment]
The same problem with Compute Graphics happens with 21.10, but in this case it happens right after the first reboot and after the login screen. I can pull up a terminal but after trying to login it immediately freezes and shows these errors:

```
nvidia 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
snd_hda_intel 000:01:00.1: can't change power state from D3Cold to D0 (config space inaccessible)
```
The only way I have found around it is instead of trying to use the GUI login going directly to the terminal using ```sudo apt purge ~nnvidia```  and rebooting.

This can also happen with Integrated Graphics on 21.10, but is fixed by setting to Hybrid from the terminal and rebooting. The problem here is also intermittent.

**Comment by crawfxrd** [comment]
pop-os/system76-power#329 may avoid the issue by disabling runtime PM for compute mode.

**Comment by n3m0-22** [comment]
With https://github.com/pop-os/system76-power/pull/329 installed on 22.04 the intermittent issues of a black screen after decryption still occurs for all graphics modes. Once successfully booted into the desktop in compute mode I tested suspend and resume using ```fwts``` with no issues.

**Comment by jackpot51** [comment]
@n3m0-22 can you try it again? Make sure to add `master` staging as well.

**Comment by n3m0-22** [comment]
Sure, I'll do that right now.

**Review by n3m0-22 — COMMENTED** [review]
# 22.04 on gaze15 tested the following

## Notes

- **NVIDIA mode (*using fwts to suspend/resume 8 pass 1 fail screenshot below*)**

- **NVIDIA mode caused Nautilus to crash**

- **mDP not working in any mode**

- **Only once when switching between Hybrid and Compute mode black screen after decryption (*could not reproduce*)**

- **No USB-C monitor to test with**

## Laptop graphics (switchable graphics)

- [x] After update and reboot, the machine remained in Hybrid graphics mode.
- [x] Switching between modes from GUI and terminal
- [ ] No problems between reboots

### Hybrid mode tests

- [x] Laptop suspends and resumes
- [x] `nvidia-smi` correctly reports the GPU's status
- [ ] DisplayPort (mDP) outputs (including sound) work as expected
- [x] HDMI-out (including sound) works as expected
- [x] External display becomes primary display when laptop lid is closed

### NVIDIA mode tests

- [ ] Laptop suspends and resumes
- [x] `nvidia-smi` correctly reports the GPU's status
- [ ] DisplayPort (mDP) outputs (including sound) work as expected
- [x] HDMI-out (including sound) works as expected
- [x] External display becomes primary display when laptop lid is closed

### Compute mode tests

- [x] `nvidia-smi` correctly reports the GPU's status
- [ ] Plugging in a display correctly prompts to switch to Hybrid mode

### Integrated mode test

- [ ] Plugging in a display correctly prompts to switch to Hybrid mode

## Software tests

These can be done on any machine with an NVIDIA GPU

- [x] NVIDIA X Server Settings application launches properly
- [x] A Unigine benchmark performs as expected
- [x] Steam can be installed and launched
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

**Referenced in notes**
22 04-470-integrated-partial

**Comment by n3m0-22** [comment]
# 22.04 on orpy4 tested the following

## Notes

- **Switching to NVIDIA mode from the menu caused the screen to lock while it was still switching (*no issues after unlocking and restart, does not happen if using terminal to switch*)**

- **In NVIDIA mode connecting through HDMI to an external monitor with a lower default resolution sets the external monitor to default and blacks out the laptop. TTY and reboot is required to reset. (*this is not an issue if the laptop is set to the same or lower resolution*)**

- **Neither Integrated nor Compute mode prompts to switch to Hybrid mode for HDMI or mDP**

- **No USB-C monitor to test with**

## Laptop graphics (switchable graphics)

- [x] After update and reboot, the machine remained in Hybrid graphics mode.
- [x] Switching between modes from GUI and terminal
- [x] No problems between reboots

### Hybrid mode tests

- [x] Laptop suspends and resumes
- [x] `nvidia-smi` correctly reports the GPU's status
- [x] DisplayPort (mDP) outputs (including sound) work as expected
- [x] HDMI-out (including sound) works as expected
- [x] External display becomes primary display when laptop lid is closed

### NVIDIA mode tests

- [x] Laptop suspends and resumes
- [x] `nvidia-smi` correctly reports the GPU's status
- [x] DisplayPort (mDP) outputs (including sound) work as expected
- [x] HDMI-out (including sound) works as expected
- [x] External display becomes primary display when laptop lid is closed

### Compute mode tests

- [x] `nvidia-smi` correctly reports the GPU's status
- [ ] Plugging in a display correctly prompts to switch to Hybrid mode

### Integrated mode test

- [ ] Plugging in a display correctly prompts to switch to Hybrid mode

## Software tests

These can be done on any machine with an NVIDIA GPU

- [x] NVIDIA X Server Settings application launches properly
- [x] A Unigine benchmark performs as expected
- [x] Steam can be installed and launched
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

**Comment by jackpot51** [comment]
There are too many regressions with this driver, please test #3 instead.

**Pull request closed without merging**
