### PR TITLE
Add patch for linux 6.2

### PR DESCRIPTION
**Pull request by 13r0ck**
For https://github.com/pop-os/linux/pull/228

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
I'm still seeing errors installing this.

[nvidia-470-patch.txt](https://github.com/pop-os/nvidia-graphics-drivers-470/files/10853950/nvidia-470-patch.txt)

**Comment by 13r0ck** [comment]
Try again now please

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — APPROVED** [review]
Looks good. The issue is resolved.

**Comment by jackpot51** [comment]
@n3m0-22 does this pass QA testing and is therefore ready to merge?

**Comment by n3m0-22** [comment]
I am in the process of updating my results in https://github.com/pop-os/linux/pull/228, but I have seen no issues with the 470 driver in combination with the 6.2 kernel.

It will still need desktop testing though to confirm.

**Comment by XV-02** [comment]
Looks good on `Oryp9` and `Mira-R3` with a gt710 onboard. Should be good to go.

**Pull request merged**
